global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gotube-api"
    static_configs:
      - targets: ["api:8080"]
    metrics_path: /metrics

  - job_name: "gotube-worker"
    static_configs:
      - targets: ["worker:9091"]
    metrics_path: /metrics
